413 logical nodes
qiskit-community/qiskit-qec pull request #414
Opened 2023-12-15 13:36 UTC by quantumjim

### Summary

fixes #413 

### Details and comments

2024-02-16 18:21 UTC, grace-harper requested changes
Just wanted to check in about the pybind11. Everything else looks good. The pymatching integration is super cool.

2024-02-16 18:21 UTC, grace-harper commented on extern/pybind11/tests/test_gil_scoped.py
Hey, just to check, did you make code modifications to `pybind11` or just the reformatting? 
If it's just the reformatting, I think we should split this PR into 2, one for all the Simplify Matching Decoding stuff and one for the reformatting of `pybind11` 
(Fwiw, given that `pybind11` is in `extern` and perhaps should even be a submodule, I don't personally feel like we necessarily have to reformat it, but definitely let me know if you feel differently)

2024-02-16 20:44 UTC, quantumjim commented on extern/pybind11/tests/test_gil_scoped.py
The reformatting of that folder was unintentional, so I reverted it.

2024-02-19 15:25 UTC, grace-harper approved these changes
LGTM

2024-02-20 11:34 UTC, quantumjim commented
Since #420 was based on this branch, that PR also covers all the changes here

2024-02-20 11:34 UTC, closed without merging